### ISSUE TITLE
value of $\tau$

### ISSUE THREAD

**Issue by thomascong121** [PhilipChicco/FRMIL#1]
Hi Thanks for the great work, I wonder how this $\tau$ value in Eq. 1 is calculated? In the paper, it is said `τ is the pre-defined maximum feature magnitude determined on the trainset only i.e., point at which the distributions first meet`, can you please provide any codes for this calculation?

**Comment by PhilipChicco** [comment]
Hi Thomas, $\tau$ can be estimated by first plotting the distributions as shown in Figure 1 of the main paper. You can refer to the code in `plots_cm16.py` to get the gist. Alternatively, you can set $\tau =  10$  or $\tau =  100$, depending on the task this should still allow the model to learn separability between classes. Hope this helps.
